server:
  port: 8081

spring:
  application:
    name: auth-domain-service

  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/auth_db
    username: postgres
    password: password

  jackson:
    time-zone: UTC

jwt:
  secret: WnN5cXhYc1dRREZsU3Z3aFZtUjRjZ3ZrNnZkS0R5cXl0a1lLZw==
  access-expiration: 3600
  refresh-expiration: 604800
